apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: category-match
spec:
  template:
    spec:
      containers:
        - name: main
          image: 0hyeon/fastapi-server:0.0.2  # 자신의 Docker 이미지를 사용
          command: ['/bin/bash', '-c']
          args:
            - git clone https://github.com/0hyeon/fast-campus-lecture &&
              cd fast-campus-lecture/lecture_1/deploy/worker/src &&
              python main.py
          volumeMounts:
            - name: nfs-volume
              mountPath: /data
      volumes:
        - name: nfs-volume
          persistentVolumeClaim:
            claimName: nfs-pvc
  # 여기서 autoscaling을 설정할 수 있습니다
  autoscaling:
    minScale: 1  # 최소 1개의 인스턴스를 유지
    maxScale: 50  # 최대 5개의 인스턴스로 오토스케일링
